kind = "mobile"
previewPath = "/"
title = "Mall Horror"
version = "1.0.0"
id = "artifacts/mall-horror"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 25383

[services.development]
run = "pnpm --filter @workspace/mall-horror run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mall-horror", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/mall-horror", "run", "serve" ]

[services.env]
PORT = "25383"
BASE_PATH = "/"
